// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function BatchAdd(arg1) {
  return window['go']['main']['App']['BatchAdd'](arg1);
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function GetRuleText() {
  return window['go']['main']['App']['GetRuleText']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function ListSubscriptions() {
  return window['go']['main']['App']['ListSubscriptions']();
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function RefreshSubscription() {
  return window['go']['main']['App']['RefreshSubscription']();
}

export function SaveRuleText(arg1) {
  return window['go']['main']['App']['SaveRuleText'](arg1);
}

export function SetPeer(arg1, arg2) {
  return window['go']['main']['App']['SetPeer'](arg1, arg2);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
